version: '3'
services:
  rest:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - "4567:4567"
  db:
    image: "mysql:5.7.27"
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=hibernate
      - MYSQL_PASSWORD=hibernate
      - MYSQL_DATABASE=pokemon_db
      - MYSQL_RANDOM_ROOT_PASSWORD=yes